# Site settings
title: WEAR LEDS!
header-img: img/home-bg.jpg
email: info@wear-leds.com
description: "the wearable LEDs"
baseurl: ""
url: ""
facebook_username: wearleds
twitter_username: wearleds
instagram_username: wearleds
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
